######################################################################
# Automatically generated by qmake (3.0) Tue Apr 4 09:28:22 2017
######################################################################

QT += widgets
QT += sql
QT += core network

TEMPLATE = app
TARGET = dev_ste
INCLUDEPATH += .

# Input
HEADERS += inc/MainWindow.h
SOURCES += src/main.cpp src/MainWindow.cpp
